### ISSUE TITLE
document.write() causes errors in Chrome

### ISSUE THREAD

**Issue by peeech** [Holo-Host/loader#6]
The way that we replace html is frowned upon by Google. A non-standard feature of blocking document.write() in certain situations causes problems while using loader.

Possible solutions:
- load content of the hApp into iframe
- use `document.getElementsByTagName('html')[0].innerHTML = html` instead of document.write()

**Comment by paulbhartzog-holo** [comment]
Is this resolved with the new loader iframe code?

**Comment by peeech** [comment]
Yes. New loader is using iFrame instead of document.write()
